name: '🗄️ Documentation'
description: Create a new ticket for documentation you would like to create or would like creating.
title: '🗄️ [Documentation] - <title>'
labels: ['documentation']
body:
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: Please enter an explicit description of what you would like documenting
      placeholder: Short and explicit description of your idea...
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: 'Screenshots'
      description: If applicable, add screenshots to help explain what you would like documenting.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: dropdown
    id: category
    attributes:
      label: 'Category'
      description: What category does this idea fall into?
      multiple: true
      options:
        - Accounts
        - Backup & Restore
        - Budgeting
        - Development
        - Installation & Configuration
        - Overview
        - Reports
        - Troubleshooting
    validations:
      required: true
